export type CefrLevel = "B2" | "C1" | "C2";

export type WordEntry = {
  id: string;
  word: string;
  level: CefrLevel;
  partOfSpeech: string;
  meaning: string;
  definition: string;
  example: string;
};

const make = (
  word: string,
  level: CefrLevel,
  partOfSpeech: string,
  meaning: string,
  definition: string,
  example: string
): WordEntry => ({
  id: level.toLowerCase() + "-" + word.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  word,
  level,
  partOfSpeech,
  meaning,
  definition,
  example
});

export const WORDS: WordEntry[] = [
  make("allocate","B2","verb","phân bổ","to give something to someone for a particular purpose","We allocate two hours a week to deliberate practice."),
  make("ambiguous","B2","adjective","mơ hồ, đa nghĩa","having more than one possible meaning","The instruction was ambiguous, so everyone interpreted it differently."),
  make("anticipate","B2","verb","dự đoán, lường trước","to expect something and prepare for it","We anticipated heavy traffic and left home early."),
  make("apparent","B2","adjective","rõ ràng, có vẻ","easy to notice or understand","It became apparent that the first plan would not work."),
  make("arbitrary","B2","adjective","tùy ý, độc đoán","based on chance or personal choice rather than a clear reason","The deadline felt arbitrary because no release depended on it."),
  make("coherent","B2","adjective","mạch lạc","logical and well organized","She gave a coherent explanation of the entire process."),
  make("compelling","B2","adjective","thuyết phục, hấp dẫn","very convincing or interesting","The data provides a compelling reason to change the strategy."),
  make("comprehensive","B2","adjective","toàn diện","including almost all important details","We need a comprehensive checklist before deployment."),
  make("consecutive","B2","adjective","liên tiếp","following one after another without interruption","He studied for ten consecutive days."),
  make("constraint","B2","noun","ràng buộc, hạn chế","something that limits what you can do","Time is the biggest constraint on this project."),
  make("counterpart","B2","noun","đối tác/vị trí tương ứng","a person or thing with the same role in another place","I discussed the issue with my counterpart in Singapore."),
  make("derive","B2","verb","suy ra, bắt nguồn","to obtain something from a source","Most of the value is derived from consistent practice."),
  make("diminish","B2","verb","giảm bớt","to become or make something smaller or less important","The effect may diminish over time."),
  make("disrupt","B2","verb","làm gián đoạn","to prevent something from continuing normally","A network failure disrupted the meeting."),
  make("elaborate","B2","verb","giải thích thêm","to add more detail to an explanation","Could you elaborate on the final requirement?"),
  make("empirical","B2","adjective","dựa trên thực nghiệm","based on observation or experience rather than theory","The team wants empirical evidence before changing the model."),
  make("feasible","B2","adjective","khả thi","possible and practical to do","A smaller release is more feasible this week."),
  make("fluctuate","B2","verb","dao động","to change frequently between different levels","Energy levels can fluctuate throughout the day."),
  make("fundamental","B2","adjective","cốt lõi, cơ bản","forming the necessary base of something","Sleep is fundamental to good concentration."),
  make("incentive","B2","noun","động lực, ưu đãi","something that encourages a person to act","A visible streak can be a useful incentive."),
  make("inevitable","B2","adjective","không thể tránh khỏi","certain to happen","Some mistakes are inevitable while learning."),
  make("inherent","B2","adjective","vốn có","existing as a natural or basic part of something","There is inherent uncertainty in every estimate."),
  make("interpret","B2","verb","diễn giải","to decide what the meaning of something is","Different readers may interpret the sentence differently."),
  make("legitimate","B2","adjective","chính đáng, hợp lệ","reasonable, acceptable, or allowed","That is a legitimate concern about privacy."),
  make("marginal","B2","adjective","nhỏ, không đáng kể","very small in amount or effect","The second optimization produced only a marginal improvement."),
  make("notion","B2","noun","khái niệm, quan niệm","an idea or belief about something","He rejected the notion that fluency requires perfect grammar."),
  make("offset","B2","verb","bù đắp","to balance the effect of something","Extra practice can offset a weak start."),
  make("persistent","B2","adjective","kiên trì; dai dẳng","continuing for a long time despite difficulty","Persistent effort usually beats occasional intensity."),
  make("plausible","B2","adjective","có vẻ hợp lý","seeming likely to be true or possible","Her explanation sounds plausible."),
  make("predominant","B2","adjective","chiếm ưu thế","more noticeable or important than others","English is the predominant language in the documentation."),
  make("profound","B2","adjective","sâu sắc","having a strong or deep effect","Daily reading had a profound effect on his vocabulary."),
  make("reluctant","B2","adjective","miễn cưỡng","not willing or eager to do something","She was reluctant to speak before she felt prepared."),
  make("retain","B2","verb","ghi nhớ, giữ lại","to keep or continue to have something","Examples help learners retain new vocabulary."),
  make("rigorous","B2","adjective","nghiêm ngặt, chặt chẽ","careful, thorough, and exact","The experiment followed a rigorous method."),
  make("subsequent","B2","adjective","tiếp theo","happening after something else","Subsequent attempts were much faster."),
  make("subtle","B2","adjective","tinh tế, khó nhận thấy","not obvious and therefore difficult to notice","There is a subtle difference between the two expressions."),
  make("sustainable","B2","adjective","bền vững","able to continue for a long time","Five words a day is a sustainable target."),
  make("tentative","B2","adjective","tạm thời, chưa chắc chắn","not yet certain or final","We made a tentative plan for next week."),
  make("trigger","B2","verb","kích hoạt, gây ra","to cause something to start","One notification can trigger a useful study habit."),
  make("underlying","B2","adjective","nền tảng, ẩn bên dưới","basic and responsible for something although not obvious","We should fix the underlying cause, not just the symptom."),

  make("alleviate","C1","verb","làm giảm nhẹ","to make pain or a problem less severe","A short break can alleviate mental fatigue."),
  make("articulate","C1","verb","diễn đạt rõ ràng","to express an idea clearly and effectively","She can articulate complex ideas in simple language."),
  make("assert","C1","verb","khẳng định","to state something firmly as true","The report asserts that the change reduced errors."),
  make("bolster","C1","verb","củng cố","to support or strengthen something","Good examples bolster the main argument."),
  make("concede","C1","verb","thừa nhận","to admit that something is true, often unwillingly","He conceded that the simpler design was better."),
  make("contemplate","C1","verb","cân nhắc kỹ","to think carefully about doing something","We are contemplating a complete rewrite."),
  make("conventional","C1","adjective","truyền thống, thông thường","following what is generally done or believed","The app avoids a conventional classroom feel."),
  make("corroborate","C1","verb","xác nhận bằng bằng chứng","to provide evidence that supports a statement","The logs corroborate the user's description of the bug."),
  make("cumulative","C1","adjective","tích lũy","increasing by adding more over time","Small daily gains create a cumulative advantage."),
  make("deem","C1","verb","cho rằng, coi là","to consider something in a particular way","The release was deemed stable enough for production."),
  make("deteriorate","C1","verb","xấu đi","to become worse","Performance may deteriorate if the cache is disabled."),
  make("discrepancy","C1","noun","sự chênh lệch, không khớp","a difference between things that should be the same","We found a discrepancy between the two reports."),
  make("disseminate","C1","verb","phổ biến, lan truyền","to spread information widely","The team disseminates release notes after every update."),
  make("distort","C1","verb","bóp méo","to change information so it becomes inaccurate","A small sample can distort the overall picture."),
  make("elicit","C1","verb","gợi ra, khơi ra","to cause or encourage a response","The question was designed to elicit a detailed answer."),
  make("encompass","C1","verb","bao gồm","to include a wide range of things","The course encompasses speaking, reading, and writing."),
  make("exacerbate","C1","verb","làm trầm trọng hơn","to make a bad situation worse","Skipping sleep can exacerbate concentration problems."),
  make("explicit","C1","adjective","rõ ràng, minh thị","stated clearly and directly","Make the success criteria explicit."),
  make("foster","C1","verb","thúc đẩy, nuôi dưỡng","to encourage the development of something","Weekly reviews foster long-term recall."),
  make("hinder","C1","verb","cản trở","to make it difficult for something to happen","Too many notifications can hinder deep work."),
  make("imminent","C1","adjective","sắp xảy ra","likely to happen very soon","A production release is imminent."),
  make("implicit","C1","adjective","ngầm hiểu","suggested without being stated directly","There was an implicit assumption that everyone agreed."),
  make("indispensable","C1","adjective","không thể thiếu","absolutely necessary","Feedback is indispensable for deliberate practice."),
  make("infer","C1","verb","suy luận","to form a conclusion from evidence","We can infer the user's intent from the previous steps."),
  make("intricate","C1","adjective","phức tạp, tinh vi","having many connected details","The animation contains several intricate transitions."),
  make("mitigate","C1","verb","giảm thiểu","to reduce the harmful effect of something","Caching can mitigate temporary network issues."),
  make("nuanced","C1","adjective","có nhiều sắc thái","showing small but important differences","The issue requires a more nuanced explanation."),
  make("obsolete","C1","adjective","lỗi thời","no longer useful because something newer exists","That API has become obsolete."),
  make("pervasive","C1","adjective","lan rộng, phổ biến","existing or spreading through every part of something","Mobile usage is pervasive among young learners."),
  make("precedent","C1","noun","tiền lệ","an earlier event used as an example for later decisions","This decision may set a precedent for future projects."),
  make("reconcile","C1","verb","dung hòa, làm cho nhất quán","to make two different ideas or facts compatible","We need to reconcile the design with the technical constraints."),
  make("redundant","C1","adjective","dư thừa","not needed because something else does the same job","The second button is redundant."),
  make("resilient","C1","adjective","bền bỉ, phục hồi tốt","able to recover quickly from difficulty","A resilient system can tolerate temporary failures."),
  make("scrutinize","C1","verb","xem xét kỹ","to examine something very carefully","Reviewers will scrutinize the final report."),
  make("sporadic","C1","adjective","rời rạc, thất thường","happening occasionally and irregularly","Sporadic practice is less effective than a daily routine."),
  make("streamline","C1","verb","tinh gọn","to make a process simpler and more efficient","We streamlined the onboarding flow."),
  make("substantiate","C1","verb","chứng minh bằng bằng chứng","to show that a claim is true with evidence","You should substantiate the claim with data."),
  make("tangible","C1","adjective","hữu hình, rõ rệt","clear enough to be seen, felt, or measured","The new workflow produced tangible benefits."),
  make("transient","C1","adjective","tạm thời, thoáng qua","lasting only a short time","The outage was transient."),
  make("viable","C1","adjective","có khả năng hoạt động","capable of working successfully","The prototype is now a viable product."),

  make("abstruse","C2","adjective","khó hiểu, uyên áo","difficult to understand, especially because it is technical","The paper is useful but unnecessarily abstruse."),
  make("acrimonious","C2","adjective","gay gắt, cay độc","full of anger and harsh words","The debate became acrimonious after the final proposal."),
  make("ameliorate","C2","verb","cải thiện, làm tốt hơn","to make an unpleasant situation better","The redesign should ameliorate several usability problems."),
  make("anachronistic","C2","adjective","lỗi thời, không hợp thời","belonging to a period different from the present","The old approval process feels increasingly anachronistic."),
  make("assiduous","C2","adjective","chăm chỉ, cần mẫn","showing great care and continuous effort","Her assiduous practice produced remarkable progress."),
  make("circumspect","C2","adjective","thận trọng","careful to consider risks before acting","Be circumspect when changing production data."),
  make("cogent","C2","adjective","thuyết phục, chặt chẽ","clear, logical, and convincing","He presented a cogent argument for simplifying the system."),
  make("concomitant","C2","adjective","đi kèm","naturally happening or existing with another thing","Growth brings a concomitant increase in operational complexity."),
  make("conundrum","C2","noun","bài toán khó, tình thế nan giải","a difficult problem with no obvious solution","Balancing speed and quality is a familiar conundrum."),
  make("deleterious","C2","adjective","có hại","causing harm or damage","Chronic sleep loss has deleterious effects on attention."),
  make("didactic","C2","adjective","mang tính giáo huấn","intended to teach, sometimes too obviously","The story is educational without becoming overly didactic."),
  make("equivocal","C2","adjective","mơ hồ, nước đôi","not clear and possibly having more than one meaning","His answer was deliberately equivocal."),
  make("esoteric","C2","adjective","chuyên sâu, ít người hiểu","understood by only a small number of people with special knowledge","The discussion became too esoteric for new team members."),
  make("fastidious","C2","adjective","cực kỳ tỉ mỉ, khó tính","very attentive to detail and accuracy","She is fastidious about naming conventions."),
  make("fortuitous","C2","adjective","tình cờ nhưng may mắn","happening by chance, often with a good result","A fortuitous conversation led to the solution."),
  make("incontrovertible","C2","adjective","không thể bác bỏ","impossible to deny or dispute","The logs provide incontrovertible evidence of the failure."),
  make("ineffable","C2","adjective","khó diễn tả thành lời","too great or unusual to be expressed in words","The first successful launch brought an ineffable sense of relief."),
  make("intransigent","C2","adjective","không khoan nhượng","unwilling to change an opinion or agreement","An intransigent stance can block useful compromise."),
  make("laconic","C2","adjective","ngắn gọn, ít lời","using very few words","His laconic reply was simply: Ship it."),
  make("magnanimous","C2","adjective","cao thượng, rộng lượng","generous and forgiving, especially toward a rival","She was magnanimous in victory and praised the other team."),
  make("meticulous","C2","adjective","tỉ mỉ","extremely careful about small details","He keeps meticulous notes during every experiment."),
  make("obfuscate","C2","verb","làm rối, che mờ","to make something harder to understand","Too much jargon can obfuscate a simple idea."),
  make("ostensibly","C2","adverb","bề ngoài thì, có vẻ như","appearing to be true although perhaps not actually true","The change was ostensibly minor but affected the whole workflow."),
  make("paradigm","C2","noun","mô hình tư duy","a typical model or pattern of something","Remote work changed the traditional office paradigm."),
  make("perfunctory","C2","adjective","qua loa, chiếu lệ","done with little care or interest","A perfunctory review can miss serious defects."),
  make("perspicacious","C2","adjective","sáng suốt, tinh tường","quick to notice and understand difficult things","Her perspicacious comments exposed the real design flaw."),
  make("pragmatic","C2","adjective","thực dụng, thực tế","dealing with problems in a practical way","We took a pragmatic approach and shipped the smallest useful version."),
  make("proliferate","C2","verb","sinh sôi, tăng nhanh","to increase rapidly in number","Small configuration files can proliferate across a large project."),
  make("quintessential","C2","adjective","điển hình nhất","being the most typical example of something","Consistency is the quintessential habit behind language learning."),
  make("recalcitrant","C2","adjective","ngoan cố, khó kiểm soát","unwilling to obey or change","The recalcitrant bug only appeared under heavy load."),
  make("reticent","C2","adjective","kín tiếng, dè dặt","unwilling to speak openly","He was reticent about discussing the unfinished feature."),
  make("sagacious","C2","adjective","khôn ngoan, sáng suốt","showing good judgment and understanding","Her sagacious advice saved the team several weeks."),
  make("salient","C2","adjective","nổi bật, quan trọng","most noticeable or important","The summary should highlight the most salient findings."),
  make("superfluous","C2","adjective","thừa thãi","more than is needed or wanted","Remove any superfluous animation from the checkout flow."),
  make("tenuous","C2","adjective","mong manh, yếu","weak, slight, or not strongly supported","The connection between the two events is tenuous."),
  make("trenchant","C2","adjective","sắc bén","expressed clearly and effectively, often critically","The reviewer made a trenchant observation about the architecture."),
  make("ubiquitous","C2","adjective","có mặt khắp nơi","seeming to be everywhere","Smartphones are ubiquitous in daily life."),
  make("vacillate","C2","verb","dao động, do dự","to keep changing between different opinions","Do not vacillate endlessly between two equally good options."),
  make("verisimilitude","C2","noun","vẻ chân thực","the appearance of being true or real","Natural dialogue gives the simulation greater verisimilitude."),
  make("vindicate","C2","verb","chứng minh là đúng","to prove that a decision or belief was correct","The final results vindicated the team's cautious approach.")
];

export const WORDS_BY_ID = Object.fromEntries(
  WORDS.map((word) => [word.id, word])
) as Record<string, WordEntry>;
